spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/employee
    username: postgres
    password: postgresql
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
