spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/tasksapipatterns}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgresql}
  jpa:
    hibernate:
      ddl-auto: create-drop
